---
# handlers file for grub

# handlers file for grub
- name: update grub
  ansible.builtin.command: "{{ grub_update_grub_command }} -o {{ grub_cfg_path }}/grub.cfg"
  when: ansible_virtualization_type not in _container_types
  notify: reboot

- name: reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when:
    - grub_allow_reboot
    - ansible_virtualization_type not in _container_types
